// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK1fdsdcvc3ZDPCaakOlrQv10OxrS1Tvc',
    appId: '1:621168795418:web:35bd6e8fa0d94281ff16a3',
    messagingSenderId: '621168795418',
    projectId: 'pet-adoption-89a32',
    authDomain: 'pet-adoption-89a32.firebaseapp.com',
    storageBucket: 'pet-adoption-89a32.firebasestorage.app',
    measurementId: 'G-FEL29XRYYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA6KgbO67mbK9oxgZPfU86y1HDGo0QIh0',
    appId: '1:621168795418:android:598a684e9b9aa593ff16a3',
    messagingSenderId: '621168795418',
    projectId: 'pet-adoption-89a32',
    storageBucket: 'pet-adoption-89a32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDzCZETQUuQHrKM81jru-S7tKtTIzrMRQ',
    appId: '1:621168795418:ios:b4eb6e071a5a7334ff16a3',
    messagingSenderId: '621168795418',
    projectId: 'pet-adoption-89a32',
    storageBucket: 'pet-adoption-89a32.firebasestorage.app',
    iosClientId: '621168795418-6p9231paiah2lbehcphnj37v6o6o85rh.apps.googleusercontent.com',
    iosBundleId: 'com.example.semesterProjectUprmPetAdoption',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDzCZETQUuQHrKM81jru-S7tKtTIzrMRQ',
    appId: '1:621168795418:ios:b4eb6e071a5a7334ff16a3',
    messagingSenderId: '621168795418',
    projectId: 'pet-adoption-89a32',
    storageBucket: 'pet-adoption-89a32.firebasestorage.app',
    iosClientId: '621168795418-6p9231paiah2lbehcphnj37v6o6o85rh.apps.googleusercontent.com',
    iosBundleId: 'com.example.semesterProjectUprmPetAdoption',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK1fdsdcvc3ZDPCaakOlrQv10OxrS1Tvc',
    appId: '1:621168795418:web:245addb9e84511dbff16a3',
    messagingSenderId: '621168795418',
    projectId: 'pet-adoption-89a32',
    authDomain: 'pet-adoption-89a32.firebaseapp.com',
    storageBucket: 'pet-adoption-89a32.firebasestorage.app',
    measurementId: 'G-80DRK7FSCT',
  );

}